# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-13 14:02
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import system.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='文章标题')),
                ('keywords', models.CharField(blank=True, max_length=50, null=True, verbose_name='关键字')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='描述')),
                ('litpic', models.ImageField(blank=True, max_length=128, null=True, storage=system.storage.ImageStorage(), upload_to='20211013', verbose_name='缩略图URL')),
                ('click', models.IntegerField(default=0, verbose_name='浏览数')),
                ('senddate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pubdate', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '文章标题',
                'verbose_name_plural': '文章标题',
            },
        ),
        migrations.CreateModel(
            name='ArcType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topid', models.IntegerField(blank=True, null=True)),
                ('typename', models.CharField(max_length=20, unique=True, verbose_name='栏目名称')),
                ('seotitle', models.CharField(blank=True, max_length=50, null=True, verbose_name='SEO标题')),
                ('keywords', models.CharField(blank=True, max_length=30, null=True, verbose_name='关键字')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='描述')),
                ('sitepath', models.SlugField(blank=True, max_length=20, null=True, verbose_name='栏目URL')),
                ('reid', models.ForeignKey(blank=True, max_length=5, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.ArcType')),
            ],
            options={
                'verbose_name': '栏目',
                'verbose_name_plural': '栏目',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='文章主体')),
                ('arc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.Archives', verbose_name='文章ID')),
            ],
            options={
                'verbose_name': '文章主体',
                'verbose_name_plural': '文章主体',
            },
        ),
        migrations.AddField(
            model_name='archives',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserInfo', verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='archives',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ArcType', verbose_name='归类'),
        ),
    ]
