# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-15 04:11
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arctype',
            name='write',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='封面主体'),
        ),
        migrations.AlterField(
            model_name='archives',
            name='litpic',
            field=models.ImageField(blank=True, max_length=128, null=True, storage=system.storage.ImageStorage(), upload_to='20211015', verbose_name='缩略图URL'),
        ),
    ]
