# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-16 07:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import system.storage


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0003_auto_20211015_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='昵称')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='手机号')),
                ('user', models.OneToOneField(max_length=20, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.AlterField(
            model_name='archives',
            name='litpic',
            field=models.ImageField(blank=True, max_length=128, null=True, storage=system.storage.ImageStorage(), upload_to='20211016', verbose_name='缩略图URL'),
        ),
        migrations.AlterField(
            model_name='archives',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ArcType', verbose_name='分类'),
        ),
    ]
