# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-02 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20211016_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archives',
            options={'verbose_name': '文章标题', 'verbose_name_plural': '文章列表'},
        ),
        migrations.AlterField(
            model_name='archives',
            name='litpic',
            field=models.ImageField(blank=True, max_length=128, null=True, storage=system.storage.ImageStorage(), upload_to='20211102', verbose_name='缩略图URL'),
        ),
    ]
